name: CHANGE-ME
recipe: wordpress
config:
  webroot: .
  xdebug: true
  php: '7.0'
  via: apache
  database: mariadb

services:
  database:
    creds:
      user: wordpress
      password: wordpress
      database: wordpress

  mailhog:
    type: mailhog
    hogfrom:
      - appserver

  node-cli:
    type: node
    globals:
      gulp-cli: latest
proxy:
  mailhog:
    - mailhog.addservices.lndo.site

tooling:
  phpunit:
    service: appserver
    description: "Run PHPUnit Tests: lando phpunit"
  composer:
    service: appserver
    description: "Run Composer: lando composer"
    cmd:
      - composer
      - --ansi
  npm:
    service: node-cli
  node:
    service: node-cli
  gulp:
    service: node-cli